// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtp3Czw2Iyd244N5qY6Bba-ujdztF55r4',
    appId: '1:313212064092:web:1a06ef6a7ae3b160e87199',
    messagingSenderId: '313212064092',
    projectId: 'books-application-f40db',
    authDomain: 'books-application-f40db.firebaseapp.com',
    storageBucket: 'books-application-f40db.appspot.com',
    measurementId: 'G-Z07QDFHP27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkbIRFC16s-oDh5oMXN3yjM370olEFzVg',
    appId: '1:313212064092:android:2439b72f0b52441be87199',
    messagingSenderId: '313212064092',
    projectId: 'books-application-f40db',
    storageBucket: 'books-application-f40db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDe1WHJr1DpL66SgppwdG8NNqGSzbfP8s',
    appId: '1:313212064092:ios:1ac98dfac6d0f741e87199',
    messagingSenderId: '313212064092',
    projectId: 'books-application-f40db',
    storageBucket: 'books-application-f40db.appspot.com',
    iosClientId: '313212064092-171bmq0i5vutrktfofeue2gg71pmrmht.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDe1WHJr1DpL66SgppwdG8NNqGSzbfP8s',
    appId: '1:313212064092:ios:1ac98dfac6d0f741e87199',
    messagingSenderId: '313212064092',
    projectId: 'books-application-f40db',
    storageBucket: 'books-application-f40db.appspot.com',
    iosClientId: '313212064092-171bmq0i5vutrktfofeue2gg71pmrmht.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookAplication',
  );
}
